apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
    pod-template-hash: b8c55bcbd
  name: mealie-b8c55bcbd-568ds
  namespace: mealie
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  type: LoadBalancer
